/**
 * Claude forum participant — Anthropic Agent SDK, in-process.
 *
 * Mirrors /api/chat/stream's use of `query()`, with two deliberate changes:
 *
 *  1. **Research tools only.** A forum is a discussion surface. Claude gets
 *     read + search + web, and explicitly NOT Write/Edit/Bash. Two agents
 *     talking to each other with shell access is a different (much larger)
 *     feature; see FORUM_READ_TOOLS below.
 *  2. **Bounded turns.** `maxTurns` is small — a forum participant is meant
 *     to answer, not to run a 40-step agentic loop while everyone waits.
 */

import {
  query,
  type CanUseTool,
  type PermissionResult,
} from "@anthropic-ai/claude-agent-sdk";
import { resolveClaudePath } from "@/lib/ai/agentClient";
import { buildSciencedashSdkServer } from "@/lib/mcp/sdkServer";
import type {
  DriverContext,
  ForumTurnEvent,
  ForumTurnResult,
  ParticipantDriver,
} from "@/lib/forum/types";

/**
 * Read-and-research surface. No Write, no Edit, no Bash — a forum discusses,
 * it doesn't mutate. The ScienceDash tools are the read pair only; a
 * participant that wanted to record a decision would go through the human.
 */
const FORUM_READ_TOOLS = [
  "Read",
  "Glob",
  "Grep",
  "WebSearch",
  "WebFetch",
  "mcp__sciencedash__query_entity",
  "mcp__sciencedash__get_entity",
];

const FORUM_READ_TOOLS_SET = new Set(FORUM_READ_TOOLS);

/**
 * Strict allowlist — unlike the chat surface, this does NOT wave through
 * every `mcp__sciencedash__*` tool. The chat surface can afford that because
 * a human typed each turn; here the turns are generated by another model.
 */
const canUseForumTool: CanUseTool = async (
  toolName: string,
  input: Record<string, unknown>,
): Promise<PermissionResult> => {
  if (FORUM_READ_TOOLS_SET.has(toolName)) {
    return { behavior: "allow", updatedInput: input };
  }
  return {
    behavior: "deny",
    message: `tool ${toolName} is not available in a forum (discussion surface: read + web only)`,
  };
};

export const claudeDriver: ParticipantDriver = {
  id: "claude",

  async speak(prompt: string, ctx: DriverContext): Promise<ForumTurnResult> {
    const events: ForumTurnEvent[] = [];
    const push = (e: ForumTurnEvent) => {
      events.push(e);
      ctx.onEvent(e);
    };

    const textParts: string[] = [];
    let sessionRef: string | null = ctx.sessionRef;
    let costUsd: number | null = null;
    let error: string | null = null;

    const ac = new AbortController();
    const onAbort = () => ac.abort(ctx.signal.reason);
    if (ctx.signal.aborted) ac.abort(ctx.signal.reason);
    else ctx.signal.addEventListener("abort", onAbort, { once: true });

    try {
      const claudePath = await resolveClaudePath();

      const q = query({
        prompt,
        options: {
          systemPrompt: ctx.systemPrompt,
          model: ctx.model,
          cwd: ctx.cwd,
          tools: FORUM_READ_TOOLS,
          canUseTool: canUseForumTool,
          mcpServers: { sciencedash: buildSciencedashSdkServer() },
          // A forum turn is one contribution to a conversation. Enough turns
          // to read a few files or run a search, not enough to disappear
          // into an agentic loop while the other participants wait.
          maxTurns: 12,
          settingSources: [],
          abortController: ac,
          ...(claudePath ? { pathToClaudeCodeExecutable: claudePath } : {}),
          ...(ctx.sessionRef ? { resume: ctx.sessionRef } : {}),
          env: {
            ...process.env,
            CLAUDE_AGENT_SDK_CLIENT_APP: "sciencedash/0.1-forum",
          },
        },
      });

      for await (const msg of q) {
        const m = msg as {
          type: string;
          subtype?: string;
          session_id?: string;
          message?: { content?: unknown };
          result?: string;
          total_cost_usd?: number;
          is_error?: boolean;
        };

        if (m.type === "system" && m.subtype === "init" && m.session_id) {
          sessionRef = m.session_id;
          continue;
        }

        if (m.type === "assistant") {
          const blocks = Array.isArray(m.message?.content)
            ? (m.message!.content as Array<Record<string, unknown>>)
            : [];
          for (const b of blocks) {
            if (b.type === "text" && typeof b.text === "string") {
              textParts.push(b.text);
              push({ kind: "text", text: b.text });
            } else if (b.type === "thinking" && typeof b.thinking === "string") {
              push({ kind: "reasoning", text: b.thinking });
            } else if (b.type === "tool_use") {
              push({
                kind: "tool_use",
                name: typeof b.name === "string" ? b.name : "?",
                input: b.input,
              });
            }
          }
          continue;
        }

        if (m.type === "user") {
          const blocks = Array.isArray(m.message?.content)
            ? (m.message!.content as Array<Record<string, unknown>>)
            : [];
          for (const b of blocks) {
            if (b.type !== "tool_result") continue;
            push({
              kind: "tool_result",
              content: b.content,
              isError: b.is_error === true,
            });
          }
          continue;
        }

        if (m.type === "result") {
          costUsd = typeof m.total_cost_usd === "number" ? m.total_cost_usd : null;
          if (m.is_error === true) {
            error = m.result?.trim() || `turn ended with subtype=${m.subtype}`;
          }
          // The SDK's result message terminates the iterator; break to make
          // that explicit rather than relying on it.
          break;
        }
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e ?? "unknown");
      error = message;
      push({ kind: "error", message });
    } finally {
      ctx.signal.removeEventListener("abort", onAbort);
    }

    return {
      text: textParts.join("\n").trim(),
      sessionRef,
      costUsd,
      events,
      error,
    };
  },
};
